# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DesertLab' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DesertLab

  target 'DesertLab-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DesertLabTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DesertLab-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DesertLab-tvOS

  target 'DesertLab-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
